title: Spend over £500 - Devon County Council 
description: Data published by Devon County COuncil - we are testing the open data capabilites of GitHub and tools developed by the ODI; used here to demonstrate the open data publishing template in Github.

publisher_text: Devon County Council
publisher_url: http://www.devon.gov.uk

license_text: UK Open Government Licence (OGL)
license_url: http://reference.data.gov.uk/id/open-government-licence

frequency: Monthly

certificate_embed: <script src='https://certificates.theodi.org/en/datasets/214377/certificate/badge.js'></script>
